/*
 Navicat Premium Data Transfer

 Source Server         : 财务
 Source Server Type    : MySQL
 Source Server Version : 80013
 Source Host           : pc-2ze310c8v8184x0r5.rwlb.rds.aliyuncs.com:3306
 Source Schema         : ads_finance

 Target Server Type    : MySQL
 Target Server Version : 80013
 File Encoding         : 65001

 Date: 08/07/2026 14:24:20
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for eb_overseas_tk_affiliate_creator
-- ----------------------------
DROP TABLE IF EXISTS `eb_overseas_tk_affiliate_creator`;
CREATE TABLE `eb_overseas_tk_affiliate_creator`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order ID',
  `product_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product ID',
  `product_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product Name',
  `sku_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU ID',
  `price` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Price',
  `payment_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Payment Amount',
  `currency` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Currency',
  `quantity` int(11) NULL DEFAULT NULL COMMENT 'Quantity',
  `fully_returned_or_refunded` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Fully returned or refunded',
  `payment_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Payment method',
  `order_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order Status',
  `creator_username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Creator Username',
  `content_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Content Type',
  `content_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Content ID',
  `commission_model` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'commission model',
  `standard_commission_rate` decimal(10, 4) NULL DEFAULT NULL COMMENT 'Standard commission rate',
  `est_commission_base` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. Commission Base',
  `est_standard_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. standard commission payment',
  `actual_commission_base` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual Commission Base',
  `actual_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual Commission Payment',
  `shop_ads_commission_rate` decimal(10, 4) NULL DEFAULT NULL COMMENT 'Shop Ads commission rate',
  `est_shop_ads_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. Shop Ads commission payment',
  `actual_shop_ads_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual Shop Ads commission payment',
  `est_co_funded_creator_bonus` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. co-funded creator bonus',
  `actual_co_funded_creator_bonus` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual co-funded creator bonus',
  `platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Platform',
  `store_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` int(11) NULL DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` json NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  `time_created` datetime NULL DEFAULT NULL COMMENT 'Time Created',
  `payment_time` datetime NULL DEFAULT NULL COMMENT 'Payment time',
  `order_delivery_time` datetime NULL DEFAULT NULL COMMENT 'Order Delivery Time',
  `time_commission_paid` datetime NULL DEFAULT NULL COMMENT 'Time Commission Paid',
  `pit_withholding_rate` decimal(10, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `est_pit` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `actual_pit` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `idx_order_id`(`order_id`, `sku_id`) USING BTREE,
  INDEX `idx_store_id`(`store_id`) USING BTREE,
  INDEX `idx_excel_order_id`(`excel_order_id`) USING BTREE,
  INDEX `idx_import_time`(`import_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 308234 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '联盟达人佣金(Affiliate-Creator orders)' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for eb_overseas_tk_affiliate_partner
-- ----------------------------
DROP TABLE IF EXISTS `eb_overseas_tk_affiliate_partner`;
CREATE TABLE `eb_overseas_tk_affiliate_partner`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order ID',
  `product_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product ID',
  `product_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product Name',
  `sku_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Sku Id',
  `price` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Price',
  `payment_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Payment Amount',
  `currency` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Currency',
  `quantity` int(11) NULL DEFAULT NULL COMMENT 'Quantity',
  `fully_returned_or_refunded` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Fully returned or refunded',
  `payment_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Payment method',
  `order_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order Status',
  `est_commission_base` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. Commission Base',
  `actual_commission_base` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual Commission Base',
  `commission_rate` decimal(10, 4) NULL DEFAULT NULL COMMENT 'Commission Rate (%)',
  `est_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. Commission Payment',
  `actual_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual Commission Payment',
  `shop_ads_commission_rate` decimal(10, 4) NULL DEFAULT NULL COMMENT 'Shop Ads commission rate',
  `est_shop_ads_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. Shop Ads commission payment',
  `actual_shop_ads_commission_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual Shop Ads commission payment',
  `partner_campaign_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Partner campaign ID',
  `affiliate_partner_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Affiliate Partner ID',
  `affiliate_partner_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Affiliate Partner Name',
  `affiliate_partner_commission_rate` decimal(10, 4) NULL DEFAULT NULL COMMENT 'Affiliate Partner Commission Rate',
  `est_commission_for_affiliate_partner` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. Commission for Affiliate Partner',
  `actual_commission_for_affiliate_partner` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Actual Commission for Affiliate Partner',
  `platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Platform',
  `store_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` int(11) NULL DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` json NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  `time_created` datetime NULL DEFAULT NULL COMMENT 'Time Created',
  `payment_time` datetime NULL DEFAULT NULL COMMENT 'Payment time',
  `order_delivery_time` datetime NULL DEFAULT NULL COMMENT 'Order Delivery Time',
  `time_commission_paid` datetime NULL DEFAULT NULL COMMENT 'Time Commission Paid',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `idx_order_id`(`order_id`, `sku_id`) USING BTREE,
  INDEX `idx_store_id`(`store_id`) USING BTREE,
  INDEX `idx_excel_order_id`(`excel_order_id`) USING BTREE,
  INDEX `idx_import_time`(`import_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 73366 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '联盟服务商佣金(Affiliate-Partner orders)' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for eb_overseas_tk_finance_on_hold
-- ----------------------------
DROP TABLE IF EXISTS `eb_overseas_tk_finance_on_hold`;
CREATE TABLE `eb_overseas_tk_finance_on_hold`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Type',
  `order_adjustment_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order/adjustment ID',
  `total_estimated_settlement_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Total estimated settlement amount',
  `unsettled_reasons` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'unsettled reasons',
  `related_order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Related order ID',
  `sku_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU ID',
  `quantity` int(11) NULL DEFAULT NULL COMMENT 'Quantity',
  `product_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product name',
  `sku_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU name',
  `net_sales` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Net sales',
  `gross_sales` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Gross sales',
  `gross_sales_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Gross sales refund',
  `seller_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller discount',
  `seller_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller discount refund',
  `fees` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Fees',
  `transaction_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Transaction fee',
  `referral_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Referral fee',
  `refund_administration_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Refund administration fee',
  `est_affiliate_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Est. affiliate commission',
  `affiliate_partner_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate partner commission',
  `affiliate_shop_ads_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate Shop Ads commission',
  `tiktok_shop_partner_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop Partner commission',
  `co_funded_promotion_seller_funded` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Co-funded promotion (seller-funded)',
  `smart_promotion_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion fee tax',
  `co_funded_creator_bonus` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Co-funded creator bonus',
  `affiliate_commission_deposit` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate commission deposit',
  `affiliate_commission_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate commission refund',
  `affiliate_partner_shop_ads_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate Partner shop ads commission',
  `campaign_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Campaign service fee',
  `campaign_resource_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Campaign resource fee',
  `sales_tax_on_referral_fees` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Sales tax on referral fees',
  `smart_promotion_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion fee',
  `managed_service_plan_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Managed service plan (Sales tax)',
  `managed_service_plan_per_order_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Managed service plan (Per order fee)',
  `co_funded_promotion_campaign_period_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee',
  `smart_promotion_campaign_period_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion campaign period fee',
  `co_funded_promotion_campaign_period_fee_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee sales tax',
  `smart_promotion_campaign_period_fee_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion campaign period fee sales tax',
  `gmv_max_coupon` decimal(18, 4) NULL DEFAULT NULL COMMENT 'GMV Max coupon',
  `gmv_max_coupon_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'GMV Max coupon sales tax',
  `gmv_max_ad_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'GMV Max ad fee',
  `category_led_campaign_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Category-led campaign fee',
  `category_led_campaign_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Category-led campaign fee tax',
  `brand_amplification_program_commission_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand Amplification Program commission fee',
  `brand_amplification_program_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand Amplification Program fee tax',
  `brand_campaign_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand campaign fee',
  `brand_campaign_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand campaign fee tax',
  `shipping` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping',
  `tiktok_shop_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping fee',
  `fulfilled_by_tiktok_shop_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Fulfilled by TikTok Shop shipping fee',
  `signature_confirmation_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Signature confirmation service fee',
  `shipping_insurance_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping insurance fee',
  `customer_paid_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer-paid shipping fee',
  `customer_paid_shipping_fee_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer-paid shipping fee refund',
  `tiktok_shop_shipping_incentive` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping incentive',
  `tiktok_shop_shipping_incentive_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping incentive refund',
  `shipping_fee_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping fee subsidy',
  `return_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping fee',
  `fbt_fulfillment_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT fulfillment fee',
  `customer_shipping_fee_offset` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer shipping fee offset',
  `shipping_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping fee discount',
  `return_shipping_label_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping label fee',
  `fbt_fulfillment_fee_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT fulfillment fee reimbursement',
  `return_shipping_fee_paid_by_customers` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping fee (paid by customers)',
  `return_shipping_fee_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping fee reimbursement',
  `shipping_app_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping app service fee',
  `shipping_protection_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping protection service fee',
  `shipping_protection_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping protection reimbursement',
  `fbt_overall_merchant_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT overall merchant subsidy',
  `fbt_key_merchant_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT key merchant subsidy',
  `adjustment_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Adjustment amount',
  `adjustment_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Adjustment reason',
  `customer_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer payment',
  `customer_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer refund',
  `seller_co_funded_voucher_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller co-funded voucher discount',
  `seller_co_funded_voucher_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller co-funded voucher discount refund',
  `platform_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform discounts',
  `platform_discounts_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform discounts refund',
  `platform_co_funded_voucher_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform co-funded voucher discounts',
  `platform_co_funded_voucher_discounts_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform co-funded voucher discounts refund',
  `sales_tax_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Sales tax payment',
  `sales_tax_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Sales tax refund',
  `retail_delivery_fee_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Retail delivery fee payment',
  `retail_delivery_fee_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Retail delivery fee refund',
  `customer_paid_shipping_fee_before_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer-paid shipping fee before discounts',
  `seller_shipping_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller shipping fee discount',
  `tiktok_shop_shipping_fee_discount_to_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping fee discount to customer',
  `mode_of_tiktok_shop_shipping_fee_discount_to_customer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Mode of TikTok Shop shipping fee discount to customer',
  `estimated_chargeable_package_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'Estimated chargeable package weight',
  `chargeable_package_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'Chargeable package weight',
  `fbt_chargeable_goods_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'FBT Chargeable goods weight',
  `collection_methods` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Collection methods',
  `delivery_option` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Delivery option',
  `store_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` int(11) NULL DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` json NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  `creation_date` datetime NULL DEFAULT NULL COMMENT 'creation date',
  `estimated_settle_time` datetime NULL DEFAULT NULL COMMENT 'Estimated Settle time',
  `order_created_date` datetime NULL DEFAULT NULL COMMENT 'Order created date',
  `order_shipment_date` datetime NULL DEFAULT NULL COMMENT 'Order shipment date',
  `order_delivery_date` datetime NULL DEFAULT NULL COMMENT 'Order delivery date',
  `transaction_created_date` datetime NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `total_revenue` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `subtotal_after_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `subtotal_before_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refund_subtotal_after_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refund_subtotal_before_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `est_transaction_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `tiktok_shop_commission_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `est_seller_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `actual_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `actual_return_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refunded_customer_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `affiliate_commission_before_pit` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pit_withheld` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `affiliate_shop_ads_commission_before_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pit_withheld_from_affiliate_shop_ads_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sfp_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `bonus_cashback_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `live_specials_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `voucher_xtra_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `order_processing_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `eams_program_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `flash_sale_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `tiktok_pay_later_program_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_co_funded_voucher_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_co_funded_voucher_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `estimated_package_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `credit_card_installment_handling_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `dynamic_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sst` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `brands_crazy_deals_flash_sale_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_support_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `customers_bank_for_payment` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `logistics_protection_compensation` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `logistics_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `logistics_protection_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `seller_growth_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `gst` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sfr_compensation` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `failed_delivery_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `tiktok_shop_vat_withheld` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sfr_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `estimated_settlement_time` datetime NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refund_of_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_shipping_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `customer_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pre_order_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `order_settled_date` datetime NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `currency` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `total_settlement_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `distance_item_fee_from_horizon_program` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_commission_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `mall_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `payment_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `commission_fee_before_savings` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `savings_from_ad_spend` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `other_commission_savings` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_costs_passed_on_to_the_logistics_provider` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `replacement_shipping_fee_passed_on_to_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `exchange_shipping_fee_passed_on_to_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost_borne_by_the_platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost_paid_by_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refunded_shipping_cost_paid_by_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `return_shipping_costs_passed_on_to_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `distance_shipping_fee_from_horizon_program` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `insurance_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `affiliate_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_fee_program_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `exclusive_benefits_access_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `dilayani_tokopedia_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `dilayani_tokopedia_handling_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pay_later_program_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `installation_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `article_22_income_tax_withheld` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_special_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `failed_delivery_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `buyer_fault_return_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `insurance_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `seller_shipping_cost_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `details_of_items_sold` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `order_source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `est_platform_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `est_payment_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `est_shipping_cost` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `credit_card_installment_interest_cost` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `customs_duty_and_vat` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `e_commerce_growth_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `infrastructure_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `idx_sku_id_order_adjustment_id`(`order_adjustment_id`, `sku_id`) USING BTREE,
  INDEX `idx_store_id`(`store_id`) USING BTREE,
  INDEX `idx_excel_order_id`(`excel_order_id`) USING BTREE,
  INDEX `idx_import_time`(`import_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 113905 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '未结算单(Finance-On hold)' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for eb_overseas_tk_finance_statements
-- ----------------------------
DROP TABLE IF EXISTS `eb_overseas_tk_finance_statements`;
CREATE TABLE `eb_overseas_tk_finance_statements`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `statement_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Statement ID',
  `payment_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Payment ID',
  `status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Status',
  `currency` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Currency',
  `type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Type',
  `order_adjustment_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order/adjustment ID',
  `sku_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU ID',
  `quantity` int(11) NULL DEFAULT NULL COMMENT 'Quantity',
  `product_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product name',
  `sku_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU name',
  `total_settlement_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Total settlement amount',
  `net_sales` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Net sales',
  `gross_sales` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Gross sales',
  `gross_sales_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Gross sales refund',
  `seller_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller discount',
  `seller_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller discount refund',
  `shipping` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping',
  `tiktok_shop_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping fee',
  `fulfilled_by_tiktok_shop_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Fulfilled by TikTok Shop shipping fee',
  `signature_confirmation_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Signature confirmation service fee',
  `shipping_insurance_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping insurance fee',
  `customer_paid_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer-paid shipping fee',
  `customer_paid_shipping_fee_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer-paid shipping fee refund',
  `tiktok_shop_shipping_incentive` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping incentive',
  `tiktok_shop_shipping_incentive_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping incentive refund',
  `shipping_fee_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping fee subsidy',
  `return_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping fee',
  `fbt_fulfillment_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT fulfillment fee',
  `customer_shipping_fee_offset` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer shipping fee offset',
  `shipping_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping fee discount',
  `return_shipping_label_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping label fee',
  `fbt_fulfillment_fee_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT fulfillment fee reimbursement',
  `return_shipping_fee_paid_by_customers` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping fee (paid by customers)',
  `return_shipping_fee_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping fee reimbursement',
  `shipping_app_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping app service fee',
  `shipping_protection_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping protection service fee',
  `shipping_protection_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping protection reimbursement',
  `fbt_overall_merchant_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT overall merchant subsidy',
  `fbt_key_merchant_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'FBT key merchant subsidy',
  `fees` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Fees',
  `transaction_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Transaction fee',
  `referral_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Referral fee',
  `refund_administration_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Refund administration fee',
  `affiliate_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate Commission',
  `affiliate_partner_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate partner commission',
  `affiliate_shop_ads_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate Shop Ads commission',
  `tiktok_shop_partner_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop Partner commission',
  `co_funded_promotion_seller_funded` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Co-funded promotion (seller-funded)',
  `smart_promotion_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion fee tax',
  `co_funded_creator_bonus` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Co-funded creator bonus',
  `affiliate_commission_deposit` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate commission deposit',
  `affiliate_commission_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate commission refund',
  `affiliate_partner_shop_ads_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Affiliate Partner shop ads commission',
  `campaign_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Campaign service fee',
  `campaign_resource_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Campaign resource fee',
  `sales_tax_on_referral_fees` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Sales tax on referral fees',
  `smart_promotion_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion fee',
  `managed_service_plan_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Managed service plan (Sales tax)',
  `managed_service_plan_per_order_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Managed service plan (Per order fee)',
  `co_funded_promotion_campaign_period_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee',
  `smart_promotion_campaign_period_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion campaign period fee',
  `co_funded_promotion_campaign_period_fee_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee sales tax',
  `smart_promotion_campaign_period_fee_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Smart Promotion campaign period fee sales tax',
  `gmv_max_coupon` decimal(18, 4) NULL DEFAULT NULL COMMENT 'GMV Max coupon',
  `gmv_max_coupon_sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'GMV Max coupon sales tax',
  `gmv_max_ad_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'GMV Max ad fee',
  `category_led_campaign_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Category-led campaign fee',
  `category_led_campaign_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Category-led campaign fee tax',
  `brand_amplification_program_commission_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand Amplification Program commission fee',
  `brand_amplification_program_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand Amplification Program fee tax',
  `brand_campaign_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand campaign fee',
  `brand_campaign_fee_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Brand campaign fee tax',
  `adjustment_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Adjustment amount',
  `adjustment_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Adjustment reason',
  `related_order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Related order ID',
  `customer_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer payment',
  `customer_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer refund',
  `seller_co_funded_voucher_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller co-funded voucher discount',
  `seller_co_funded_voucher_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller co-funded voucher discount refund',
  `platform_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform discounts',
  `platform_discounts_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform discounts refund',
  `platform_co_funded_voucher_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform co-funded voucher discounts',
  `platform_co_funded_voucher_discounts_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Platform co-funded voucher discounts refund',
  `ads_referral_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Ads referral fee discount',
  `sales_tax_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Sales tax payment',
  `sales_tax_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Sales tax refund',
  `retail_delivery_fee_payment` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Retail delivery fee payment',
  `retail_delivery_fee_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Retail delivery fee refund',
  `customer_paid_shipping_fee_before_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Customer-paid shipping fee before discounts',
  `seller_shipping_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Seller shipping fee discount',
  `tiktok_shop_shipping_fee_discount_to_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'TikTok Shop shipping fee discount to customer',
  `mode_of_tiktok_shop_shipping_fee_discount_to_customer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Mode of TikTok Shop shipping fee discount to customer',
  `return_shipping_fee_paid_by_customers_2` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return shipping fee (paid by customers) 2',
  `estimated_chargeable_package_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'Estimated chargeable package weight',
  `chargeable_package_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'Chargeable package weight',
  `fbt_chargeable_goods_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'FBT Chargeable goods weight',
  `collection_methods` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Collection methods',
  `delivery_option` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Delivery option',
  `signature_confirmation_service_fee_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Signature confirmation service fee type',
  `store_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` int(11) NULL DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` json NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  `statement_date` datetime NULL DEFAULT NULL COMMENT 'Statement date',
  `order_created_date` datetime NULL DEFAULT NULL COMMENT 'Order created date',
  `order_shipment_date` datetime NULL DEFAULT NULL COMMENT 'Order shipment date',
  `order_delivery_date` datetime NULL DEFAULT NULL COMMENT 'Order delivery date',
  `total_revenue` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `subtotal_after_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `subtotal_before_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refund_subtotal_after_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refund_subtotal_before_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `tiktok_shop_commission_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `seller_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `actual_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `actual_return_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refunded_customer_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `affiliate_commission_before_pit` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pit_withheld` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `affiliate_shop_ads_commission_before_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pit_withheld_from_affiliate_shop_ads_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sfp_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sales_tax` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `bonus_cashback_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `live_specials_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `voucher_xtra_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `order_processing_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `eams_program_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `flash_sale_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `tiktok_pay_later_program_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_co_funded_voucher_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_co_funded_voucher_discount_refund` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `estimated_package_weight` decimal(14, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `credit_card_installment_handling_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `dynamic_commission` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sst` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `brands_crazy_deals_flash_sale_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_support_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `customers_bank_for_payment` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `logistics_protection_compensation` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `logistics_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `logistics_protection_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `seller_growth_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `gst` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `order_settled_date` datetime NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sfr_compensation` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `failed_delivery_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `tiktok_shop_vat_withheld` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `sfr_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refund_of_seller_discounts` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_shipping_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `customer_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pre_order_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `distance_item_fee_from_horizon_program` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_commission_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `mall_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `payment_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `commission_fee_before_savings` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `savings_from_ad_spend` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `other_commission_savings` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_costs_passed_on_to_the_logistics_provider` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `replacement_shipping_fee_passed_on_to_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `exchange_shipping_fee_passed_on_to_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost_borne_by_the_platform` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost_paid_by_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `refunded_shipping_cost_paid_by_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `return_shipping_costs_passed_on_to_the_customer` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_cost_subsidy` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `distance_shipping_fee_from_horizon_program` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `insurance_reimbursement` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_fee_program_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `exclusive_benefits_access_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `dilayani_tokopedia_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `dilayani_tokopedia_handling_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `pay_later_program_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `installation_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `article_22_income_tax_withheld` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `platform_special_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `failed_delivery_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `buyer_fault_return_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `insurance_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `seller_shipping_cost_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `details_of_items_sold` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `order_source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `credit_card_installment_interest_cost` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `customs_duty_and_vat` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `e_commerce_growth_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `infrastructure_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `customs_duty` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `additional_information` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `ads_referral_fee_disccount_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `retail_delivery_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `idx_sku_id_order_adjustment_id`(`order_adjustment_id`, `sku_id`) USING BTREE,
  INDEX `idx_store_id`(`store_id`) USING BTREE,
  INDEX `idx_excel_order_id`(`excel_order_id`) USING BTREE,
  INDEX `idx_import_time`(`import_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 508431 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '结算表-Order details(Finance-Statements)' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for eb_overseas_tk_order
-- ----------------------------
DROP TABLE IF EXISTS `eb_overseas_tk_order`;
CREATE TABLE `eb_overseas_tk_order`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order ID',
  `order_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order Status',
  `order_substatus` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order Substatus',
  `cancelation_return_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Cancelation/Return Type',
  `normal_or_pre_order` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Normal or Pre-order',
  `sku_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU ID',
  `seller_sku` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Seller SKU',
  `product_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product Name',
  `variation` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Variation',
  `virtual_bundle_seller_sku` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Virtual Bundle Seller SKU',
  `quantity` int(11) NULL DEFAULT NULL COMMENT 'Quantity',
  `sku_quantity_of_return` int(11) NULL DEFAULT NULL COMMENT 'Sku Quantity of return',
  `sku_unit_original_price` decimal(18, 4) NULL DEFAULT NULL COMMENT 'SKU Unit Original Price',
  `sku_subtotal_before_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'SKU Subtotal Before Discount',
  `sku_platform_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'SKU Platform Discount',
  `sku_seller_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'SKU Seller Discount',
  `sku_subtotal_after_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'SKU Subtotal After Discount',
  `shipping_fee_after_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping Fee After Discount',
  `original_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Original Shipping Fee',
  `shipping_fee_seller_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping Fee Seller Discount',
  `co_funded_shipping_fee_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Co-Funded Shipping Fee Discount',
  `shipping_fee_platform_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Shipping Fee Platform Discount',
  `payment_platform_discount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Payment platform discount',
  `retail_delivery_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Retail Delivery Fee',
  `taxes` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Taxes',
  `order_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Order Amount',
  `order_refund_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Order Refund Amount',
  `cancel_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Cancel By',
  `cancel_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Cancel Reason',
  `fulfillment_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Fulfillment Type',
  `warehouse_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Warehouse Name',
  `tracking_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Tracking ID',
  `delivery_option_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Delivery Option Type',
  `delivery_option` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Delivery Option',
  `shipping_provider_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Shipping Provider Name',
  `buyer_message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Buyer Message',
  `buyer_nickname` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Buyer Nickname',
  `buyer_username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Buyer Username',
  `recipient` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Recipient',
  `phone_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Phone #',
  `country` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Country',
  `state` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'State',
  `city` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'City',
  `zipcode` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Zipcode',
  `address_line_1` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Address Line 1',
  `address_line_2` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Address Line 2',
  `delivery_instruction` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Delivery Instruction',
  `payment_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Payment Method',
  `weight_kg` decimal(14, 4) NULL DEFAULT NULL COMMENT 'Weight(kg)',
  `product_category` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product Category',
  `package_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Package ID',
  `seller_note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Seller Note',
  `shipping_information` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Shipping Information',
  `combined_listing` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Combined Listing',
  `store_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` int(11) NULL DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` json NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  `created_time` datetime NULL DEFAULT NULL COMMENT 'Created Time',
  `paid_time` datetime NULL DEFAULT NULL COMMENT 'Paid Time',
  `rts_time` datetime NULL DEFAULT NULL COMMENT 'RTS Time',
  `shipped_time` datetime NULL DEFAULT NULL COMMENT 'Shipped Time',
  `delivered_time` datetime NULL DEFAULT NULL COMMENT 'Delivered Time',
  `cancelled_time` datetime NULL DEFAULT NULL COMMENT 'Cancelled Time',
  `province` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `district` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `commune` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `detail_address` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `additional_address_information` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `checked_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `checked_marked_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `post_town` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `region` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `municipality` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `barangay` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `unit_floor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `distance_shipping_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `distance_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `buyer_service_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `handling_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `shipping_insurance` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `item_insurance` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  `regency_and_city` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `districts` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `villages` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `purchase_channel` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `tokopedia_invoice_number` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'auto-added from excel',
  `small_order_fee` decimal(18, 4) NULL DEFAULT NULL COMMENT 'auto-added from excel',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `ids_order_id`(`order_id`, `sku_id`) USING BTREE,
  INDEX `idx_store_id`(`store_id`) USING BTREE,
  INDEX `idx_excel_order_id`(`excel_order_id`) USING BTREE,
  INDEX `idx_import_time`(`import_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 704468 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '订单(Manage orders-All)' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Table structure for eb_overseas_tk_order_return
-- ----------------------------
DROP TABLE IF EXISTS `eb_overseas_tk_order_return`;
CREATE TABLE `eb_overseas_tk_order_return`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `return_order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Return Order ID',
  `order_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order ID',
  `order_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Order Amount',
  `order_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order Status',
  `order_substatus` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Order Substatus',
  `payment_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Payment Method',
  `sku_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU ID',
  `seller_sku` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Seller SKU',
  `product_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Product Name',
  `sku_name` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'SKU Name',
  `buyer_username` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Buyer Username',
  `return_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Return Type',
  `return_reason` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Return Reason',
  `return_unit_price` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Return unit price',
  `return_quantity` int(11) NULL DEFAULT NULL COMMENT 'Return Quantity',
  `return_logistics_tracking_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Return Logistics Tracking ID',
  `return_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Return Status',
  `return_sub_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Return Sub Status',
  `dispute_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Dispute Status',
  `appeal_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Appeal Status',
  `compensation_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Compensation Status',
  `compensation_amount` decimal(18, 4) NULL DEFAULT NULL COMMENT 'Compensation Amount',
  `buyer_note` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Buyer Note',
  `store_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` int(10) UNSIGNED NULL DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` int(11) NULL DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` json NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  `time_requested` datetime NULL DEFAULT NULL COMMENT 'Time Requested',
  `refund_time` datetime NULL DEFAULT NULL COMMENT 'Refund Time',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `ids_return_order_id`(`order_id`, `sku_id`) USING BTREE,
  INDEX `idx_store_id`(`store_id`) USING BTREE,
  INDEX `idx_excel_order_id`(`excel_order_id`) USING BTREE,
  INDEX `idx_import_time`(`import_time`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10439 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '退货退款单(Manage returns-All)' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
