-- ==========================================================================
-- TikTok 卖家后台 6 段导出 → MySQL 5.7 建表语句
-- A: 订单         B: 退货退款单    C1: 联盟达人佣金
-- C2: 联盟服务商佣金  D: 结算表       E: 未结算单
-- 公共扩展字段: id(主键), store_id(店铺外键), excel_order_id(导出批次外键), import_time(导入时间)
-- 字段命名规则: 原 Excel 表头转小写, 空格 → 下划线, 特殊符号清理
-- 金额/费用/佣金/税/补贴/重量 等字段统一 DECIMAL, 便于后续聚合统计
-- ==========================================================================

-- ===== A  订单(Manage orders-All) =====
DROP TABLE IF EXISTS `eb_overseas_tk_order`;
CREATE TABLE `eb_overseas_tk_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'Order ID',
  `order_status` VARCHAR(255) DEFAULT NULL COMMENT 'Order Status',
  `order_substatus` VARCHAR(255) DEFAULT NULL COMMENT 'Order Substatus',
  `cancelation_return_type` VARCHAR(255) DEFAULT NULL COMMENT 'Cancelation/Return Type',
  `normal_or_pre_order` VARCHAR(255) DEFAULT NULL COMMENT 'Normal or Pre-order',
  `sku_id` VARCHAR(64) DEFAULT NULL COMMENT 'SKU ID',
  `seller_sku` VARCHAR(255) DEFAULT NULL COMMENT 'Seller SKU',
  `product_name` VARCHAR(500) DEFAULT NULL COMMENT 'Product Name',
  `variation` VARCHAR(255) DEFAULT NULL COMMENT 'Variation',
  `virtual_bundle_seller_sku` VARCHAR(255) DEFAULT NULL COMMENT 'Virtual Bundle Seller SKU',
  `quantity` INT DEFAULT NULL COMMENT 'Quantity',
  `sku_quantity_of_return` INT DEFAULT NULL COMMENT 'Sku Quantity of return',
  `sku_unit_original_price` DECIMAL(18, 4) DEFAULT NULL COMMENT 'SKU Unit Original Price',
  `sku_subtotal_before_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'SKU Subtotal Before Discount',
  `sku_platform_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'SKU Platform Discount',
  `sku_seller_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'SKU Seller Discount',
  `sku_subtotal_after_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'SKU Subtotal After Discount',
  `shipping_fee_after_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping Fee After Discount',
  `original_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Original Shipping Fee',
  `shipping_fee_seller_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping Fee Seller Discount',
  `co_funded_shipping_fee_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Co-Funded Shipping Fee Discount',
  `shipping_fee_platform_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping Fee Platform Discount',
  `payment_platform_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Payment platform discount',
  `retail_delivery_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Retail Delivery Fee',
  `taxes` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Taxes',
  `order_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Order Amount',
  `order_refund_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Order Refund Amount',
  `created_time` DATETIME NULL COMMENT 'Created Time',
  `paid_time` DATETIME NULL COMMENT 'Paid Time',
  `rts_time` DATETIME NULL COMMENT 'RTS Time',
  `shipped_time` DATETIME NULL COMMENT 'Shipped Time',
  `delivered_time` DATETIME NULL COMMENT 'Delivered Time',
  `cancelled_time` DATETIME NULL COMMENT 'Cancelled Time',
  `cancel_by` VARCHAR(255) DEFAULT NULL COMMENT 'Cancel By',
  `cancel_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'Cancel Reason',
  `fulfillment_type` VARCHAR(255) DEFAULT NULL COMMENT 'Fulfillment Type',
  `warehouse_name` VARCHAR(500) DEFAULT NULL COMMENT 'Warehouse Name',
  `tracking_id` VARCHAR(64) DEFAULT NULL COMMENT 'Tracking ID',
  `delivery_option_type` VARCHAR(255) DEFAULT NULL COMMENT 'Delivery Option Type',
  `delivery_option` VARCHAR(255) DEFAULT NULL COMMENT 'Delivery Option',
  `shipping_provider_name` VARCHAR(500) DEFAULT NULL COMMENT 'Shipping Provider Name',
  `buyer_message` VARCHAR(1000) DEFAULT NULL COMMENT 'Buyer Message',
  `buyer_nickname` VARCHAR(255) DEFAULT NULL COMMENT 'Buyer Nickname',
  `buyer_username` VARCHAR(255) DEFAULT NULL COMMENT 'Buyer Username',
  `recipient` VARCHAR(255) DEFAULT NULL COMMENT 'Recipient',
  `phone_no` VARCHAR(255) DEFAULT NULL COMMENT 'Phone #',
  `country` VARCHAR(255) DEFAULT NULL COMMENT 'Country',
  `state` VARCHAR(255) DEFAULT NULL COMMENT 'State',
  `city` VARCHAR(255) DEFAULT NULL COMMENT 'City',
  `zipcode` VARCHAR(255) DEFAULT NULL COMMENT 'Zipcode',
  `address_line_1` VARCHAR(500) DEFAULT NULL COMMENT 'Address Line 1',
  `address_line_2` VARCHAR(500) DEFAULT NULL COMMENT 'Address Line 2',
  `delivery_instruction` VARCHAR(255) DEFAULT NULL COMMENT 'Delivery Instruction',
  `payment_method` VARCHAR(255) DEFAULT NULL COMMENT 'Payment Method',
  `weight_kg` DECIMAL(14, 4) DEFAULT NULL COMMENT 'Weight(kg)',
  `product_category` VARCHAR(500) DEFAULT NULL COMMENT 'Product Category',
  `package_id` VARCHAR(64) DEFAULT NULL COMMENT 'Package ID',
  `seller_note` VARCHAR(1000) DEFAULT NULL COMMENT 'Seller Note',
  `shipping_information` VARCHAR(1000) DEFAULT NULL COMMENT 'Shipping Information',
  `combined_listing` VARCHAR(255) DEFAULT NULL COMMENT 'Combined Listing',
  `store_id` INT UNSIGNED DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` INT UNSIGNED DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` INT DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` VARCHAR(255) DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` JSON DEFAULT NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_excel_order_id` (`excel_order_id`),
  KEY `idx_import_time` (`import_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单(Manage orders-All)';

-- ===== B  退货退款单(Manage returns-All) =====
DROP TABLE IF EXISTS `eb_overseas_tk_order_return`;
CREATE TABLE `eb_overseas_tk_order_return` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `return_order_id` VARCHAR(64) DEFAULT NULL COMMENT 'Return Order ID',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'Order ID',
  `order_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Order Amount',
  `order_status` VARCHAR(255) DEFAULT NULL COMMENT 'Order Status',
  `order_substatus` VARCHAR(255) DEFAULT NULL COMMENT 'Order Substatus',
  `payment_method` VARCHAR(255) DEFAULT NULL COMMENT 'Payment Method',
  `sku_id` VARCHAR(64) DEFAULT NULL COMMENT 'SKU ID',
  `seller_sku` VARCHAR(255) DEFAULT NULL COMMENT 'Seller SKU',
  `product_name` VARCHAR(500) DEFAULT NULL COMMENT 'Product Name',
  `sku_name` VARCHAR(500) DEFAULT NULL COMMENT 'SKU Name',
  `buyer_username` VARCHAR(255) DEFAULT NULL COMMENT 'Buyer Username',
  `return_type` VARCHAR(255) DEFAULT NULL COMMENT 'Return Type',
  `time_requested` DATETIME NULL COMMENT 'Time Requested',
  `return_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'Return Reason',
  `return_unit_price` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return unit price',
  `return_quantity` INT DEFAULT NULL COMMENT 'Return Quantity',
  `return_logistics_tracking_id` VARCHAR(64) DEFAULT NULL COMMENT 'Return Logistics Tracking ID',
  `return_status` VARCHAR(255) DEFAULT NULL COMMENT 'Return Status',
  `return_sub_status` VARCHAR(255) DEFAULT NULL COMMENT 'Return Sub Status',
  `refund_time` DATETIME NULL COMMENT 'Refund Time',
  `dispute_status` VARCHAR(255) DEFAULT NULL COMMENT 'Dispute Status',
  `appeal_status` VARCHAR(255) DEFAULT NULL COMMENT 'Appeal Status',
  `compensation_status` VARCHAR(255) DEFAULT NULL COMMENT 'Compensation Status',
  `compensation_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Compensation Amount',
  `buyer_note` VARCHAR(1000) DEFAULT NULL COMMENT 'Buyer Note',
  `store_id` INT UNSIGNED DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` INT UNSIGNED DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` INT DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` VARCHAR(255) DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` JSON DEFAULT NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_excel_order_id` (`excel_order_id`),
  KEY `idx_import_time` (`import_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退货退款单(Manage returns-All)';

-- ===== C1  联盟达人佣金(Affiliate-Creator orders) =====
DROP TABLE IF EXISTS `eb_overseas_tk_affiliate_creator`;
CREATE TABLE `eb_overseas_tk_affiliate_creator` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'Order ID',
  `product_id` VARCHAR(64) DEFAULT NULL COMMENT 'Product ID',
  `product_name` VARCHAR(500) DEFAULT NULL COMMENT 'Product Name',
  `sku_id` VARCHAR(64) DEFAULT NULL COMMENT 'SKU ID',
  `price` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Price',
  `payment_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Payment Amount',
  `currency` VARCHAR(255) DEFAULT NULL COMMENT 'Currency',
  `quantity` INT DEFAULT NULL COMMENT 'Quantity',
  `fully_returned_or_refunded` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Fully returned or refunded',
  `payment_method` VARCHAR(255) DEFAULT NULL COMMENT 'Payment method',
  `order_status` VARCHAR(255) DEFAULT NULL COMMENT 'Order Status',
  `creator_username` VARCHAR(255) DEFAULT NULL COMMENT 'Creator Username',
  `content_type` VARCHAR(255) DEFAULT NULL COMMENT 'Content Type',
  `content_id` VARCHAR(64) DEFAULT NULL COMMENT 'Content ID',
  `commission_model` VARCHAR(255) DEFAULT NULL COMMENT 'commission model',
  `standard_commission_rate` DECIMAL(10, 4) DEFAULT NULL COMMENT 'Standard commission rate',
  `est_commission_base` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. Commission Base',
  `est_standard_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. standard commission payment',
  `actual_commission_base` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual Commission Base',
  `actual_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual Commission Payment',
  `shop_ads_commission_rate` DECIMAL(10, 4) DEFAULT NULL COMMENT 'Shop Ads commission rate',
  `est_shop_ads_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. Shop Ads commission payment',
  `actual_shop_ads_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual Shop Ads commission payment',
  `est_co_funded_creator_bonus` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. co-funded creator bonus',
  `actual_co_funded_creator_bonus` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual co-funded creator bonus',
  `time_created` DATETIME NULL COMMENT 'Time Created',
  `payment_time` DATETIME NULL COMMENT 'Payment time',
  `order_delivery_time` DATETIME NULL COMMENT 'Order Delivery Time',
  `time_commission_paid` DATETIME NULL COMMENT 'Time Commission Paid',
  `platform` VARCHAR(255) DEFAULT NULL COMMENT 'Platform',
  `store_id` INT UNSIGNED DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` INT UNSIGNED DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` INT DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` VARCHAR(255) DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` JSON DEFAULT NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_excel_order_id` (`excel_order_id`),
  KEY `idx_import_time` (`import_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='联盟达人佣金(Affiliate-Creator orders)';

-- ===== C2  联盟服务商佣金(Affiliate-Partner orders) =====
DROP TABLE IF EXISTS `eb_overseas_tk_affiliate_partner`;
CREATE TABLE `eb_overseas_tk_affiliate_partner` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` VARCHAR(64) DEFAULT NULL COMMENT 'Order ID',
  `product_id` VARCHAR(64) DEFAULT NULL COMMENT 'Product ID',
  `product_name` VARCHAR(500) DEFAULT NULL COMMENT 'Product Name',
  `sku_id` VARCHAR(64) DEFAULT NULL COMMENT 'Sku Id',
  `price` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Price',
  `payment_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Payment Amount',
  `currency` VARCHAR(255) DEFAULT NULL COMMENT 'Currency',
  `quantity` INT DEFAULT NULL COMMENT 'Quantity',
  `fully_returned_or_refunded` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Fully returned or refunded',
  `payment_method` VARCHAR(255) DEFAULT NULL COMMENT 'Payment method',
  `order_status` VARCHAR(255) DEFAULT NULL COMMENT 'Order Status',
  `est_commission_base` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. Commission Base',
  `actual_commission_base` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual Commission Base',
  `commission_rate` DECIMAL(10, 4) DEFAULT NULL COMMENT 'Commission Rate (%)',
  `est_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. Commission Payment',
  `actual_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual Commission Payment',
  `shop_ads_commission_rate` DECIMAL(10, 4) DEFAULT NULL COMMENT 'Shop Ads commission rate',
  `est_shop_ads_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. Shop Ads commission payment',
  `actual_shop_ads_commission_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual Shop Ads commission payment',
  `partner_campaign_id` VARCHAR(64) DEFAULT NULL COMMENT 'Partner campaign ID',
  `affiliate_partner_id` VARCHAR(64) DEFAULT NULL COMMENT 'Affiliate Partner ID',
  `affiliate_partner_name` VARCHAR(500) DEFAULT NULL COMMENT 'Affiliate Partner Name',
  `affiliate_partner_commission_rate` DECIMAL(10, 4) DEFAULT NULL COMMENT 'Affiliate Partner Commission Rate',
  `est_commission_for_affiliate_partner` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. Commission for Affiliate Partner',
  `actual_commission_for_affiliate_partner` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Actual Commission for Affiliate Partner',
  `time_created` DATETIME NULL COMMENT 'Time Created',
  `payment_time` DATETIME NULL COMMENT 'Payment time',
  `order_delivery_time` DATETIME NULL COMMENT 'Order Delivery Time',
  `time_commission_paid` DATETIME NULL COMMENT 'Time Commission Paid',
  `platform` VARCHAR(255) DEFAULT NULL COMMENT 'Platform',
  `store_id` INT UNSIGNED DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` INT UNSIGNED DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` INT DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` VARCHAR(255) DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` JSON DEFAULT NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_excel_order_id` (`excel_order_id`),
  KEY `idx_import_time` (`import_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='联盟服务商佣金(Affiliate-Partner orders)';

-- ===== D  结算表-Order details(Finance-Statements) =====
DROP TABLE IF EXISTS `eb_overseas_tk_finance_statements`;
CREATE TABLE `eb_overseas_tk_finance_statements` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `statement_date` DATETIME NULL COMMENT 'Statement date',
  `statement_id` VARCHAR(64) DEFAULT NULL COMMENT 'Statement ID',
  `payment_id` VARCHAR(64) DEFAULT NULL COMMENT 'Payment ID',
  `status` VARCHAR(255) DEFAULT NULL COMMENT 'Status',
  `currency` VARCHAR(255) DEFAULT NULL COMMENT 'Currency',
  `type` VARCHAR(255) DEFAULT NULL COMMENT 'Type',
  `order_adjustment_id` VARCHAR(64) DEFAULT NULL COMMENT 'Order/adjustment ID',
  `sku_id` VARCHAR(64) DEFAULT NULL COMMENT 'SKU ID',
  `quantity` INT DEFAULT NULL COMMENT 'Quantity',
  `product_name` VARCHAR(500) DEFAULT NULL COMMENT 'Product name',
  `sku_name` VARCHAR(500) DEFAULT NULL COMMENT 'SKU name',
  `order_created_date` DATETIME NULL COMMENT 'Order created date',
  `order_shipment_date` DATETIME NULL COMMENT 'Order shipment date',
  `order_delivery_date` DATETIME NULL COMMENT 'Order delivery date',
  `total_settlement_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Total settlement amount',
  `net_sales` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Net sales',
  `gross_sales` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Gross sales',
  `gross_sales_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Gross sales refund',
  `seller_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller discount',
  `seller_discount_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller discount refund',
  `shipping` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping',
  `tiktok_shop_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping fee',
  `fulfilled_by_tiktok_shop_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Fulfilled by TikTok Shop shipping fee',
  `signature_confirmation_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Signature confirmation service fee',
  `shipping_insurance_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping insurance fee',
  `customer_paid_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer-paid shipping fee',
  `customer_paid_shipping_fee_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer-paid shipping fee refund',
  `tiktok_shop_shipping_incentive` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping incentive',
  `tiktok_shop_shipping_incentive_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping incentive refund',
  `shipping_fee_subsidy` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping fee subsidy',
  `return_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping fee',
  `fbt_fulfillment_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT fulfillment fee',
  `customer_shipping_fee_offset` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer shipping fee offset',
  `shipping_fee_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping fee discount',
  `return_shipping_label_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping label fee',
  `fbt_fulfillment_fee_reimbursement` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT fulfillment fee reimbursement',
  `return_shipping_fee_paid_by_customers` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping fee (paid by customers)',
  `return_shipping_fee_reimbursement` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping fee reimbursement',
  `shipping_app_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping app service fee',
  `shipping_protection_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping protection service fee',
  `shipping_protection_reimbursement` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping protection reimbursement',
  `fbt_overall_merchant_subsidy` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT overall merchant subsidy',
  `fbt_key_merchant_subsidy` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT key merchant subsidy',
  `fees` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Fees',
  `transaction_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Transaction fee',
  `referral_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Referral fee',
  `refund_administration_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Refund administration fee',
  `affiliate_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate Commission',
  `affiliate_partner_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate partner commission',
  `affiliate_shop_ads_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate Shop Ads commission',
  `tiktok_shop_partner_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop Partner commission',
  `co_funded_promotion_seller_funded` VARCHAR(255) DEFAULT NULL COMMENT 'Co-funded promotion (seller-funded)',
  `smart_promotion_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion fee tax',
  `co_funded_creator_bonus` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Co-funded creator bonus',
  `affiliate_commission_deposit` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate commission deposit',
  `affiliate_commission_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate commission refund',
  `affiliate_partner_shop_ads_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate Partner shop ads commission',
  `campaign_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Campaign service fee',
  `campaign_resource_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Campaign resource fee',
  `sales_tax_on_referral_fees` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Sales tax on referral fees',
  `smart_promotion_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion fee',
  `managed_service_plan_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Managed service plan (Sales tax)',
  `managed_service_plan_per_order_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Managed service plan (Per order fee)',
  `co_funded_promotion_campaign_period_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee',
  `smart_promotion_campaign_period_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion campaign period fee',
  `co_funded_promotion_campaign_period_fee_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee sales tax',
  `smart_promotion_campaign_period_fee_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion campaign period fee sales tax',
  `gmv_max_coupon` DECIMAL(18, 4) DEFAULT NULL COMMENT 'GMV Max coupon',
  `gmv_max_coupon_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'GMV Max coupon sales tax',
  `gmv_max_ad_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'GMV Max ad fee',
  `category_led_campaign_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Category-led campaign fee',
  `category_led_campaign_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Category-led campaign fee tax',
  `brand_amplification_program_commission_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand Amplification Program commission fee',
  `brand_amplification_program_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand Amplification Program fee tax',
  `brand_campaign_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand campaign fee',
  `brand_campaign_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand campaign fee tax',
  `adjustment_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Adjustment amount',
  `adjustment_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'Adjustment reason',
  `related_order_id` VARCHAR(64) DEFAULT NULL COMMENT 'Related order ID',
  `customer_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer payment',
  `customer_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer refund',
  `seller_co_funded_voucher_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller co-funded voucher discount',
  `seller_co_funded_voucher_discount_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller co-funded voucher discount refund',
  `platform_discounts` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform discounts',
  `platform_discounts_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform discounts refund',
  `platform_co_funded_voucher_discounts` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform co-funded voucher discounts',
  `platform_co_funded_voucher_discounts_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform co-funded voucher discounts refund',
  `ads_referral_fee_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Ads referral fee discount',
  `sales_tax_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Sales tax payment',
  `sales_tax_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Sales tax refund',
  `retail_delivery_fee_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Retail delivery fee payment',
  `retail_delivery_fee_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Retail delivery fee refund',
  `customer_paid_shipping_fee_before_discounts` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer-paid shipping fee before discounts',
  `seller_shipping_fee_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller shipping fee discount',
  `tiktok_shop_shipping_fee_discount_to_customer` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping fee discount to customer',
  `mode_of_tiktok_shop_shipping_fee_discount_to_customer` VARCHAR(255) DEFAULT NULL COMMENT 'Mode of TikTok Shop shipping fee discount to customer',
  `return_shipping_fee_paid_by_customers_2` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping fee (paid by customers) 2',
  `estimated_chargeable_package_weight` DECIMAL(14, 4) DEFAULT NULL COMMENT 'Estimated chargeable package weight',
  `chargeable_package_weight` DECIMAL(14, 4) DEFAULT NULL COMMENT 'Chargeable package weight',
  `fbt_chargeable_goods_weight` DECIMAL(14, 4) DEFAULT NULL COMMENT 'FBT Chargeable goods weight',
  `collection_methods` VARCHAR(255) DEFAULT NULL COMMENT 'Collection methods',
  `delivery_option` VARCHAR(255) DEFAULT NULL COMMENT 'Delivery option',
  `signature_confirmation_service_fee_type` VARCHAR(255) DEFAULT NULL COMMENT 'Signature confirmation service fee type',
  `store_id` INT UNSIGNED DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` INT UNSIGNED DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` INT DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` VARCHAR(255) DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` JSON DEFAULT NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_excel_order_id` (`excel_order_id`),
  KEY `idx_import_time` (`import_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='结算表-Order details(Finance-Statements)';

-- ===== E  未结算单(Finance-On hold) =====
DROP TABLE IF EXISTS `eb_overseas_tk_finance_on_hold`;
CREATE TABLE `eb_overseas_tk_finance_on_hold` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `type` VARCHAR(255) DEFAULT NULL COMMENT 'Type',
  `order_adjustment_id` VARCHAR(64) DEFAULT NULL COMMENT 'Order/adjustment ID',
  `creation_date` DATETIME NULL COMMENT 'creation date',
  `total_estimated_settlement_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Total estimated settlement amount',
  `estimated_settle_time` DATETIME NULL COMMENT 'Estimated Settle time',
  `unsettled_reasons` VARCHAR(255) DEFAULT NULL COMMENT 'unsettled reasons',
  `related_order_id` VARCHAR(64) DEFAULT NULL COMMENT 'Related order ID',
  `order_created_date` DATETIME NULL COMMENT 'Order created date',
  `order_shipment_date` DATETIME NULL COMMENT 'Order shipment date',
  `order_delivery_date` DATETIME NULL COMMENT 'Order delivery date',
  `sku_id` VARCHAR(64) DEFAULT NULL COMMENT 'SKU ID',
  `quantity` INT DEFAULT NULL COMMENT 'Quantity',
  `product_name` VARCHAR(500) DEFAULT NULL COMMENT 'Product name',
  `sku_name` VARCHAR(500) DEFAULT NULL COMMENT 'SKU name',
  `net_sales` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Net sales',
  `gross_sales` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Gross sales',
  `gross_sales_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Gross sales refund',
  `seller_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller discount',
  `seller_discount_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller discount refund',
  `fees` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Fees',
  `transaction_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Transaction fee',
  `referral_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Referral fee',
  `refund_administration_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Refund administration fee',
  `est_affiliate_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Est. affiliate commission',
  `affiliate_partner_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate partner commission',
  `affiliate_shop_ads_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate Shop Ads commission',
  `tiktok_shop_partner_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop Partner commission',
  `co_funded_promotion_seller_funded` VARCHAR(255) DEFAULT NULL COMMENT 'Co-funded promotion (seller-funded)',
  `smart_promotion_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion fee tax',
  `co_funded_creator_bonus` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Co-funded creator bonus',
  `affiliate_commission_deposit` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate commission deposit',
  `affiliate_commission_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate commission refund',
  `affiliate_partner_shop_ads_commission` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Affiliate Partner shop ads commission',
  `campaign_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Campaign service fee',
  `campaign_resource_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Campaign resource fee',
  `sales_tax_on_referral_fees` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Sales tax on referral fees',
  `smart_promotion_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion fee',
  `managed_service_plan_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Managed service plan (Sales tax)',
  `managed_service_plan_per_order_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Managed service plan (Per order fee)',
  `co_funded_promotion_campaign_period_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee',
  `smart_promotion_campaign_period_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion campaign period fee',
  `co_funded_promotion_campaign_period_fee_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Co-funded Promotion campaign period fee sales tax',
  `smart_promotion_campaign_period_fee_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Smart Promotion campaign period fee sales tax',
  `gmv_max_coupon` DECIMAL(18, 4) DEFAULT NULL COMMENT 'GMV Max coupon',
  `gmv_max_coupon_sales_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'GMV Max coupon sales tax',
  `gmv_max_ad_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'GMV Max ad fee',
  `category_led_campaign_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Category-led campaign fee',
  `category_led_campaign_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Category-led campaign fee tax',
  `brand_amplification_program_commission_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand Amplification Program commission fee',
  `brand_amplification_program_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand Amplification Program fee tax',
  `brand_campaign_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand campaign fee',
  `brand_campaign_fee_tax` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Brand campaign fee tax',
  `shipping` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping',
  `tiktok_shop_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping fee',
  `fulfilled_by_tiktok_shop_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Fulfilled by TikTok Shop shipping fee',
  `signature_confirmation_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Signature confirmation service fee',
  `shipping_insurance_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping insurance fee',
  `customer_paid_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer-paid shipping fee',
  `customer_paid_shipping_fee_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer-paid shipping fee refund',
  `tiktok_shop_shipping_incentive` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping incentive',
  `tiktok_shop_shipping_incentive_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping incentive refund',
  `shipping_fee_subsidy` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping fee subsidy',
  `return_shipping_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping fee',
  `fbt_fulfillment_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT fulfillment fee',
  `customer_shipping_fee_offset` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer shipping fee offset',
  `shipping_fee_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping fee discount',
  `return_shipping_label_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping label fee',
  `fbt_fulfillment_fee_reimbursement` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT fulfillment fee reimbursement',
  `return_shipping_fee_paid_by_customers` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping fee (paid by customers)',
  `return_shipping_fee_reimbursement` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Return shipping fee reimbursement',
  `shipping_app_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping app service fee',
  `shipping_protection_service_fee` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping protection service fee',
  `shipping_protection_reimbursement` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Shipping protection reimbursement',
  `fbt_overall_merchant_subsidy` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT overall merchant subsidy',
  `fbt_key_merchant_subsidy` DECIMAL(18, 4) DEFAULT NULL COMMENT 'FBT key merchant subsidy',
  `adjustment_amount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Adjustment amount',
  `adjustment_reason` VARCHAR(1000) DEFAULT NULL COMMENT 'Adjustment reason',
  `customer_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer payment',
  `customer_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer refund',
  `seller_co_funded_voucher_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller co-funded voucher discount',
  `seller_co_funded_voucher_discount_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller co-funded voucher discount refund',
  `platform_discounts` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform discounts',
  `platform_discounts_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform discounts refund',
  `platform_co_funded_voucher_discounts` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform co-funded voucher discounts',
  `platform_co_funded_voucher_discounts_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Platform co-funded voucher discounts refund',
  `sales_tax_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Sales tax payment',
  `sales_tax_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Sales tax refund',
  `retail_delivery_fee_payment` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Retail delivery fee payment',
  `retail_delivery_fee_refund` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Retail delivery fee refund',
  `customer_paid_shipping_fee_before_discounts` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Customer-paid shipping fee before discounts',
  `seller_shipping_fee_discount` DECIMAL(18, 4) DEFAULT NULL COMMENT 'Seller shipping fee discount',
  `tiktok_shop_shipping_fee_discount_to_customer` DECIMAL(18, 4) DEFAULT NULL COMMENT 'TikTok Shop shipping fee discount to customer',
  `mode_of_tiktok_shop_shipping_fee_discount_to_customer` VARCHAR(255) DEFAULT NULL COMMENT 'Mode of TikTok Shop shipping fee discount to customer',
  `estimated_chargeable_package_weight` DECIMAL(14, 4) DEFAULT NULL COMMENT 'Estimated chargeable package weight',
  `chargeable_package_weight` DECIMAL(14, 4) DEFAULT NULL COMMENT 'Chargeable package weight',
  `fbt_chargeable_goods_weight` DECIMAL(14, 4) DEFAULT NULL COMMENT 'FBT Chargeable goods weight',
  `collection_methods` VARCHAR(255) DEFAULT NULL COMMENT 'Collection methods',
  `delivery_option` VARCHAR(255) DEFAULT NULL COMMENT 'Delivery option',
  `store_id` INT UNSIGNED DEFAULT NULL COMMENT '所属店铺ID(外键, 关联店铺表主键)',
  `excel_order_id` INT UNSIGNED DEFAULT NULL COMMENT '导出批次ID(外键, 关联导出记录表主键)',
  `import_time` INT DEFAULT 0 COMMENT '数据导入时间',
  `shop_code` VARCHAR(255) DEFAULT NULL COMMENT '店铺shop_code',
  `extra_data` JSON DEFAULT NULL COMMENT '动态字段池：存储所有店铺不一致的字段',
  PRIMARY KEY (`id`),
  KEY `idx_store_id` (`store_id`),
  KEY `idx_excel_order_id` (`excel_order_id`),
  KEY `idx_import_time` (`import_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='未结算单(Finance-On hold)';
